### PR TITLE
Added Images to each member mentioned on the about page

### PR DESCRIPTION
**Pull request by yashb196**
What was changed?

Image of each person mentioned in the about page is added along with links to each tech lead's portfolio/github.

Why was it changed?

Initially on the about page only the names were mentioned for each of the tech leads (current and previous) with no details. This does not promote the tech leads and the projects.

How was it changed?

Added images in a circular format and added a link to each tech leads github/portfolio.

Screenshots that show the changes (if applicable):
Screenshot 2024-03-15 at 1 16 07 PM
Screenshot 2024-03-15 at 1 16 16 PM
Screenshot 2024-03-15 at 1 16 22 PM

New Layout 

Screenshot 2024-03-15 at 1 16 32 PM
Screenshot 2024-03-15 at 1 16 39 PM
Screenshot 2024-03-15 at 1 16 47 PM
Screenshot 2024-03-15 at 1 16 54 PM
Screenshot 2024-03-15 at 1 17 02 PM

### CODE REVIEW

**Comment by kate-holdener** [comment]
@SiriChandanaGarimella @loganwyas Do you have a picture we can use on the oss website? @yashb196 is updating the site to include pictures, and your pictures are not there.

**Comment by loganwyas** [comment]
I do have a picture, where should I add it?

**Comment by yashb196** [comment]
> I do have a picture, where should I add it?

Add the image in static/img folder with the following format 
"name_avatar".jpg or .png

**Comment by kungfuchicken** [comment]
straight HTML works, but I'm curious if it's possible to do it with only Markdown. Does Docusauraus have some way of adding a `<div>` and/or `className`?

**Comment by yashb196** [comment]
> straight HTML works, but I'm curious if it's possible to do it with only Markdown. Does Docusauraus have some way of adding a `<div>` and/or `className`?

It is possible to do so however the file needs to be changed from a .md to a .mdx, I did not wish to alter the extension without prior permission 

https://docusaurus.io/docs/markdown-features

**Comment by kungfuchicken** [comment]
i think this is a perfect use case for MDX. go for it!

**Comment by kungfuchicken** [comment]
@cubap @thehabes @chintakjoshi your GitHub user profile pics were used here. Do you want to keep these, or provide a photo for this wonderful contribution from @yashb196 ?

**Comment by chintakjoshi** [comment]
> @cubap @thehabes @chintakjoshi your GitHub user profile pics were used here. Do you want to keep these, or provide a photo for this wonderful contribution from @yashb196 ?

I Just sent a better photo to @yashb196

**Comment by cubap** [comment]
> @cubap @thehabes @chintakjoshi your GitHub user profile pics were used here. Do you want to keep these, or provide a photo for this wonderful contribution from @yashb196 ?

I probably have one. I'll update when I'm on campus. I'm not too worried about being an avatar for a bit.

**Comment by cubap** [comment]
ahahaha! I gave a photo to AI and asked it to turn me an impressive profile pic for a software dev. It made me young and gave me a baguette. 
WhatsApp Image 2024-03-28 at 15 27 50_ab5a8fdd

**Comment by thehabes** [comment]
The profile pic says everything you need to know, keep it.

**Comment by yashb196** [comment]
> Fixed it. WhatsApp Image 2024-03-28 at 15 30 48_0f88ad6f

photo has been added 😁

**Pull request merged**
