### PR TITLE
Created portfolio for Rerum Playground in a markdown file

### PR DESCRIPTION
**Pull request by jacksayshi**
Portfolio created for the project Rerum Playground with brief description. Further details like developers list should be updated.

### CODE REVIEW

**Comment by jacksayshi** [comment]
Thank you for reviewing and providing me the feedback. I made the change you suggested and linked the page to external project section.

**Review by kungfuchicken — APPROVED** [review]
lgtm;

**Comment by kungfuchicken** [comment]
@Santosh-Iragavarapu please resolve conflict to merge.

**Comment by jacksayshi** [comment]
> @Santosh-Iragavarapu please resolve conflict to merge.

I just resolved this issue. Thank you. :)

**Review by kungfuchicken — APPROVED** [review]
lgtm;

**Pull request merged**
