### PR TITLE
Added Bubblescan and ESP projects

### PR DESCRIPTION
**Pull request by rkarmuri**

### CODE REVIEW

**Comment by kungfuchicken** [comment]
sorry, didn't realize you weren't in the right group. can you resubmit this as a branch off main instead of a fork off the repo? it's not impossible for me to review this way, just harder. i'm totally being lazy 😝

**Comment by rkarmuri** [comment]
Lol, sure. I will do that.

**Comment by rkarmuri** [comment]
Added a new branch esp-bubblescan that has the details of the bubble scan and esp projects.

**Comment by kungfuchicken** [comment]
PR moved to #60

**Comment by kungfuchicken** [comment]
#60 merged

**Pull request closed without merging**
