### PR TITLE
Blog related to Story telling in Grant writing workshop

### PR DESCRIPTION
**Pull request by AjithAkuthota23**
On 23rd October, 2024, I attended an interesting workshop on "Story telling in grant writing" and shared some insights and highlights of that workshop.

### CODE REVIEW

**Comment by kungfuchicken** [comment]
Thank you, this is coming along nicely! Please do some work to connect this to open source software and/or research software. How would the workshop apply in our specific context? I'll be able to do a more comprehensive review after Thanksgiving.

**Review by kungfuchicken — CHANGES_REQUESTED** [review]
this needs to connect to open source software and/or research software more directly. also needs a mention of the Associate Dean who facilitated a conversation. maybe you could follow up with some questions for her via e-mail that you could quote in your piece.

**Comment by AjithAkuthota23** [comment]
> this needs to connect to open source software and/or research software more directly. also needs a mention of the Associate Dean who facilitated a conversation. maybe you could follow up with some questions for her via e-mail that you could quote in your piece.

I had a conversation with her via email and got some info that I included in the blog

**Comment by AjithAkuthota23** [comment]
> Thank you, this is coming along nicely! Please do some work to connect this to open source software and/or research software. How would the workshop apply in our specific context? I'll be able to do a more comprehensive review after Thanksgiving.

Updated

**Review by kungfuchicken — APPROVED** [review]
lgtm;

**Pull request merged**
