### PR TITLE
Blog Writing about Where's Religion App Launch and Our Open Source Experience

### PR DESCRIPTION
**Pull request by BaloneyBoy97**
Write to a blog post that celebrates the work.
where's religion app launch!
app is live check it out!

### CODE REVIEW

**Comment by kungfuchicken** [comment]
This is coming along nicely! I'll do a full review after Thanksgiving.

**Review by yashb196 — DISMISSED** [review]
Looks Good

**Review by kungfuchicken — CHANGES_REQUESTED** [review]
@rcAsironman Please try to weave your contributions in throughout the post rather than just tacking on a *Karthik* section at the end. Also, please stay focused on Where's Religion and the launch. You can mention Hacktoberfest, but it can't take up as much space (on the screen or in the overall story). This post has gotten very long, and I would like both you and @BaloneyBoy97 to work together on consolidating it down a bit.

**Comment by BaloneyBoy97** [comment]
@rcAsironman , the content is good. But, you should probably move it above the mobile and web comparison section. also the second mobile sim image is blurry, could you use a screenshot for better viewing experience?

**Comment by rcAsironman** [comment]
> @rcAsironman Please try to weave your contributions in throughout the post rather than just tacking on a _Karthik_ section at the end. Also, please stay focused on Where's Religion and the launch. You can mention Hacktoberfest, but it can't take up as much space (on the screen or in the overall story). This post has gotten very long, and I would like both you and @BaloneyBoy97 to work together on consolidating it down a bit.

@kungfuchicken I have modified the blog accordin

> @rcAsironman , the content is good. But, you should probably move it above the mobile and web comparison section. also the second mobile sim image is blurry, could you use a screenshot for better viewing experience?

@BaloneyBoy97 I have update the blog as you mentioned.

**Comment by rcAsironman** [comment]
> @rcAsironman Please try to weave your contributions in throughout the post rather than just tacking on a _Karthik_ section at the end. Also, please stay focused on Where's Religion and the launch. You can mention Hacktoberfest, but it can't take up as much space (on the screen or in the overall story). This post has gotten very long, and I would like both you and @BaloneyBoy97 to work together on consolidating it down a bit.

@kungfuchicken I have made changes to the blog post as you suggested.

**Review by kungfuchicken — APPROVED** [review]
lgtm; in this case, it means "looks GREAT! to me"; thank you, @BaloneyBoy97 @rcAsironman and @yashb196 !

**Pull request merged**
