### PR TITLE
Playbook

### PR DESCRIPTION
**Pull request by kate-holdener**
Playbook for creating an open source program office at a university - the SLU way.

### CODE REVIEW

**Review by kungfuchicken — APPROVED** [review]
lgtm; i'd like to get it merged and keep working on it in smaller chunks.

**Comment by kungfuchicken** [comment]
it's blocking merge b/c i pushed commits to it. I'm okay with bypassing merge requirements once we've both looked at it, or we could have @rkarmuri give it a review.

**Comment by kate-holdener** [comment]
@kungfuchicken Your commit [3b69903](https://github.com/oss-slu/oss-slu.github.io/pull/73/commits/3b699036a0d313d735f2e42f0e8300be581fc518) removed the changes you added in commit [ae10cfa](https://github.com/oss-slu/oss-slu.github.io/pull/73/commits/ae10cfa886e9530fd596df82135b9dc223c04635). Was that intentional?

**Comment by kungfuchicken** [comment]
this is one of myriad reasons extra eyes are always good. probably bungled this when trying to do a line-by-line (instead of whole file) commit.

**Pull request merged**
