### PR TITLE
Updated Current Tech Lead Information

### LINKED ISSUE #84: Update the Tech Lead's Information in the About Page of Homeless Shelter Volunteer Scheduling Application

### PR DESCRIPTION
**Pull request by Brijitha1609**
Fixes #84 

Description: This pull request updates the current Tech Lead information on the About page.

What was changed?
Updated tech lead information in the About page.

Why was it changed?
By making these changes, the About page's content is kept up-to-date.

How was it changed?
I made the required changes in the about.md file in the information section.

### CODE REVIEW

**Review by kungfuchicken — CHANGES_REQUESTED** [review]
The core change looks good, but we really don't need to commit package-lock.json. It should probably be added to a .gitignore. This was not a major issue in the past becuase we had fewer contributors in the repo, but it has bit us at least once before. Do you mind doing that so we don't run into weird npm issues in the future?

**Comment by Brijitha1609** [comment]
I understand the concerns about not needing to commit package-lock.json due to potential npm issues with multiple contributors. However, adding package-lock.json to the .gitignore has caused some deployment issues. Specifically, I'm getting the following annotations:
1 error and 2 warnings:
Error: "Dependencies lock file is not found in /home/runner/work/oss-slu.github.io/oss-slu.github.io. Supported file patterns: package-lock.json, npm-shrinkwrap.json, yarn.lock."

**Comment by kungfuchicken** [comment]
interesting... it will take me a minute to look at it. i might just wait to push, as it could impact other people's local. i want to look closely before merging this because of that.

**Comment by kungfuchicken** [comment]
i'll have it figured out by EOW

**Review by kungfuchicken — APPROVED** [review]
these are all minor version bumps. i think it might be because yarn is doing an update or something. i've only seen package-lock.json get updated in a couple PRs. it works locally, though, with only `npm start` so i'll merge and deal with the upgrades we need to do anyway later. 

thank you for your patience!

**Pull request merged**
