### PR TITLE
Content changes to About page and Shelter Volunteers project

### PR DESCRIPTION
**Pull request by SiriChandanaGarimella**
Updated the About page and team details on the Shelter Volunteers project about page.

### CODE REVIEW

**Comment by kungfuchicken** [comment]
This looks good. One minor thing, the current developers need the `(capstone)` label added to their listings. See https://oss-slu.github.io/docs/project_pi4micronaut/about for an example. Once that's added it should be ready to go.

**Review by kungfuchicken — CHANGES_REQUESTED** [review]
This looks good. One minor thing, the current developers need the (capstone) label added to their listings. See https://oss-slu.github.io/docs/project_pi4micronaut/about for an example. Once that's added it should be ready to go.

**Comment by SiriChandanaGarimella** [comment]
Added the label capstone for current developers. Could you please check it once?

**Review by kungfuchicken — APPROVED** [review]
lgtm;

**Pull request merged**
