### PR TITLE
added new tech leads to about section

### PR DESCRIPTION
**Pull request by AbhilashKotha**
@kungfuchicken I have added the new tech leads to the list in alphabetical order.

### CODE REVIEW

**Comment by AbhilashKotha** [comment]
@kungfuchicken Please do let me know if I have to remove anyone who is no more active from the list.

**Comment by kungfuchicken** [comment]
Let's move the tech leads who have graduated into a new section. Maybe "Tech Lead Alumni" or something like that?

**Comment by yashb196** [comment]
The new commit has the required changes mentioned above 

Seperate section for 

Previous Team Leads 

Current Team Leads

**Comment by kungfuchicken** [comment]
lgtm;

**Review by kungfuchicken — APPROVED** [review]
lgtm;

**Pull request merged**
